#!/usr/bin/env node
'use strict';

/*
 * Generate the placeholder TypeScript client for the Space Stellar NFT
 * contract.
 *
 * The real, typed client is emitted by `stellar scaffold build --build-clients`.
 * This helper previously overwrote frontend/src/contracts/client.ts
 * unconditionally with a stub, silently destroying the generated client. It now
 * writes a marker into everything it produces and refuses to overwrite a file
 * that does not carry that marker unless `--force` is passed explicitly.
 */

const fs = require('fs');
const path = require('path');

// dotenv is optional: the script also works with plain environment variables.
try {
  require('dotenv').config();
} catch {
  /* no dotenv installed, nothing to load */
}

const ROOT = path.resolve(__dirname, '..');
const CONTRACT_NAME = 'SpaceStellarNFT';
const OUTPUT = path.join(ROOT, 'frontend', 'src', 'contracts', 'client.ts');
const GENERATED_MARKER = '// @generated by scripts/generate-client.js';

const force = process.argv.includes('--force');
const CONTRACT_ID = process.env.CONTRACT_ID || '';

if (!CONTRACT_ID) {
  console.warn('⚠️  CONTRACT_ID is not set; the generated client will have an empty id.');
}

const clientCode = `${GENERATED_MARKER}
// Placeholder client for ${CONTRACT_NAME}.
// Run \`stellar scaffold build --build-clients\` for the full generated client.

export const CONTRACT_ID = '${CONTRACT_ID}';

export interface ShipMetadata {
  class: string;
  rarity: string;
  tier: string;
  attack: number;
  speed: number;
  shield: number;
  ipfsCid: string;
  metadataUri: string;
}

export class ${CONTRACT_NAME}Client {
  constructor(
    public contractId: string = CONTRACT_ID,
    public network: 'testnet' | 'mainnet' = 'testnet',
  ) {}

  // Implement contract calls with @stellar/stellar-sdk here.
}

export default ${CONTRACT_NAME}Client;
`;

if (fs.existsSync(OUTPUT)) {
  const existing = fs.readFileSync(OUTPUT, 'utf8');
  if (!existing.startsWith(GENERATED_MARKER) && !force) {
    console.error(`❌ Refusing to overwrite ${path.relative(ROOT, OUTPUT)}`);
    console.error('   That file was not generated by this script (missing marker).');
    console.error('   Re-run with --force to overwrite it deliberately.');
    process.exit(1);
  }
}

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, clientCode);

console.log(`✅ TypeScript client generated at ${path.relative(ROOT, OUTPUT)}`);
